#page title
page_title                                : Grid Central                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6550893182                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ca                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Grid Central - The Ultimate Sportscar Racing App

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nathan Stehr                               
your_link                                 :                 
your_city                                 : Ottawa, Canada ðŸ‡¨ðŸ‡¦                                
email_address                             : nstehr@gmail.com
facebook_username                         :                                           
instagram_username                        : laserdeathstehr
twitter_username                          : laserdeathstehr
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Standings
    description                           : Get updates on team and manufacturer standings throughout the season.
    fontawesome_icon_name                 : flag-checkered 
    
  - title                                 : Race Schedule
    description                           : View the complete schedule of upcoming races, so you never miss a race.
    fontawesome_icon_name                 : flag-checkered 

  - title                                 : Race Results
    description                           : Access detailed race results after the checkered flag drops.
    fontawesome_icon_name                 : flag-checkered 

  - title                                 : Team Listings
    description                           : Discover the teams racing this season, their cars and where they are from.
    fontawesome_icon_name                 : flag-checkered 

  - title                                 : Widgets
    description                           : Home screen widgets to keep you up to date on the next race
    fontawesome_icon_name                 : flag-checkered



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/dreamstime_xxl_225536436.jpg                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
